# Group Guide

## Public guides listing [/guides/public/{?page,per_page}]

+ Parameters

    + page: `2` (optional, integer)
        + Default: `1`
    + per_page: `20` (optional, integer) - Number of guides to return.
        + Default: `10`

### Get a list of public guides [GET]
::: note
#### <i class="fa fa-key"></i> This entrypoint does not require authentication
:::
Return a defined number of public guides' short info. The number is defined by the `per_page` arguments. User can request other pages using the `page` arguments.

+ Response 200 (application/json)
    + Attributes(GuideInfoArray)

## Guides listing [/guides/{?page,per_page}]

+ Parameters

    + page: `2` (optional, integer)
        + Default: `1`
    + per_page: `20` (optional, integer) - Number of guides to return.
        + Default: `10`

### <i class="fa fa-key"></i> Get a list of the user guides [GET]
Return a defined number of guides' short info. The number is defined by the `per_page` arguments. User can request other pages using the `page` arguments.

+ Response 200 (application/json)
    + Attributes(GuideInfoArray)

## Guide [/guide]
### <i class="fa fa-key"></i> Create a new guide [POST]

+ Response 201

## Guide general information [/guide/{id}]

+ Parameters

    + id: `0` (required, integer)

### <i class="fa fa-key"></i> Get the information for a guide [GET]
Get the information for the given guide.

+ Response 200 (application/json)
    + Attributes(GuideInfo)

+ Response 404 (application/json)

            {
                "error": "Guide not found"
            }

### <i class="fa fa-key"></i> Modify the guide information [PATCH]
Modify the guide information. Every fields in the request body are **optional**, however, only the one shown in the example below will be recognized. Note that `last-edited` is updated automatically every time the guide is modified through this request or any other (adding photo, removing photo, etc.)

+ Request (application/json)
    + Body

            {
                "title": "Example guide",
                "featured-image": "http://foo.bar/image.jpg",
                "visibility": false
            }

+ Response 200 (application/json)
    + Attributes(GuideInfo)

+ Response 404 (application/json)

            {
                "error": "Guide not found"
            }

### <i class="fa fa-key"></i> Delete a guide [DELETE]
Delete the given guide.

+ Response 200

+ Response 404 (application/json)

            {
                "error": "Guide not found"
            }
