# Group Weather

## Weather info [/weather]

### <i class="fa fa-key"></i> Get weather report [GET]

Get the weather report for the guide.

The response is a passthrough of the wheather API.

+ Request (application/json)
    + Body

            {
                "guide_id": 0
            }

+ Response 200 (application/json)

            {
            }

+ Response 404 (application/json)

            {
                "error": "Guide not found"
            }

+ Response 400 (application/json)

            {
                "error": "No location"
            }